# Generated by Django 4.2.18 on 2025-05-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_alter_paymentsource_source_type_delete_sourcetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsource',
            name='source_type',
            field=models.CharField(choices=[('BA', 'Bank account'), ('CC', 'Credit card'), ('DW', 'Digital wallet'), ('PC', 'Prepaid card'), ('CA', 'Cash')], default='BA', max_length=2),
        ),
    ]
