# Generated by Django 4.2.18 on 2025-05-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('IDR', 'Rupiah'), ('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
