# Generated by Django 4.2.18 on 2025-07-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_alter_paymentsource_source_type'),
        ('expenses', '0005_alter_expense_source_alter_expense_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sources.paymentsource'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.store'),
        ),
    ]
