# Generated by Django 4.2.18 on 2025-08-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_source_alter_expense_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='icon',
            field=models.CharField(blank=True),
        ),
    ]
