# Generated by Django 4.2.18 on 2025-08-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expensecategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='hue',
            field=models.FloatField(null=True),
        ),
    ]
