/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLayoutSignupImport } from './routes/_authLayout/signup'
import { Route as AuthLayoutLoginImport } from './routes/_authLayout/login'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRouteRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutSignupRoute = AuthLayoutSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)

const AuthLayoutLoginRoute = AuthLayoutLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authLayout/login': {
      id: '/_authLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginImport
      parentRoute: typeof AuthLayoutRouteImport
    }
    '/_authLayout/signup': {
      id: '/_authLayout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthLayoutSignupImport
      parentRoute: typeof AuthLayoutRouteImport
    }
  }
}

// Create and export the route tree

interface AuthLayoutRouteRouteChildren {
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutSignupRoute: typeof AuthLayoutSignupRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutSignupRoute: AuthLayoutSignupRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthLayoutRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRoute
  '/login': typeof AuthLayoutLoginRoute
  '/signup': typeof AuthLayoutSignupRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthLayoutRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRoute
  '/login': typeof AuthLayoutLoginRoute
  '/signup': typeof AuthLayoutSignupRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authLayout': typeof AuthLayoutRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRoute
  '/_authLayout/login': typeof AuthLayoutLoginRoute
  '/_authLayout/signup': typeof AuthLayoutSignupRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/dashboard' | '/login' | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/dashboard' | '/login' | '/signup'
  id:
    | '__root__'
    | '/'
    | '/_authLayout'
    | '/dashboard'
    | '/_authLayout/login'
    | '/_authLayout/signup'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authLayout",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authLayout": {
      "filePath": "_authLayout/route.tsx",
      "children": [
        "/_authLayout/login",
        "/_authLayout/signup"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx"
    },
    "/_authLayout/login": {
      "filePath": "_authLayout/login.tsx",
      "parent": "/_authLayout"
    },
    "/_authLayout/signup": {
      "filePath": "_authLayout/signup.tsx",
      "parent": "/_authLayout"
    }
  }
}
ROUTE_MANIFEST_END */
