/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLayoutSignUpImport } from './routes/_authLayout/SignUp'
import { Route as AuthLayoutLoginImport } from './routes/_authLayout/Login'

// Create/Update Routes

const AuthLayoutRouteRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutSignUpRoute = AuthLayoutSignUpImport.update({
  id: '/SignUp',
  path: '/SignUp',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)

const AuthLayoutLoginRoute = AuthLayoutLoginImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authLayout/Login': {
      id: '/_authLayout/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof AuthLayoutLoginImport
      parentRoute: typeof AuthLayoutRouteImport
    }
    '/_authLayout/SignUp': {
      id: '/_authLayout/SignUp'
      path: '/SignUp'
      fullPath: '/SignUp'
      preLoaderRoute: typeof AuthLayoutSignUpImport
      parentRoute: typeof AuthLayoutRouteImport
    }
  }
}

// Create and export the route tree

interface AuthLayoutRouteRouteChildren {
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutSignUpRoute: typeof AuthLayoutSignUpRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutSignUpRoute: AuthLayoutSignUpRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthLayoutRouteRouteWithChildren
  '/Login': typeof AuthLayoutLoginRoute
  '/SignUp': typeof AuthLayoutSignUpRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthLayoutRouteRouteWithChildren
  '/Login': typeof AuthLayoutLoginRoute
  '/SignUp': typeof AuthLayoutSignUpRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authLayout': typeof AuthLayoutRouteRouteWithChildren
  '/_authLayout/Login': typeof AuthLayoutLoginRoute
  '/_authLayout/SignUp': typeof AuthLayoutSignUpRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/Login' | '/SignUp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/Login' | '/SignUp'
  id:
    | '__root__'
    | '/'
    | '/_authLayout'
    | '/_authLayout/Login'
    | '/_authLayout/SignUp'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authLayout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authLayout": {
      "filePath": "_authLayout/route.tsx",
      "children": [
        "/_authLayout/Login",
        "/_authLayout/SignUp"
      ]
    },
    "/_authLayout/Login": {
      "filePath": "_authLayout/Login.tsx",
      "parent": "/_authLayout"
    },
    "/_authLayout/SignUp": {
      "filePath": "_authLayout/SignUp.tsx",
      "parent": "/_authLayout"
    }
  }
}
ROUTE_MANIFEST_END */
