/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteRouteImport } from './routes/_dashboardLayout/route'
import { Route as AuthLayoutRouteRouteImport } from './routes/_authLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutDashboardRouteImport } from './routes/_dashboardLayout/dashboard'
import { Route as AuthLayoutSignupRouteImport } from './routes/_authLayout/signup'
import { Route as AuthLayoutLoginRouteImport } from './routes/_authLayout/login'
import { Route as AuthLayoutCheckEmailVerifyRouteImport } from './routes/_authLayout/check-email-verify'
import { Route as DashboardLayoutExpensesIndexRouteImport } from './routes/_dashboardLayout/expenses/index'
import { Route as DashboardLayoutAccountscardsIndexRouteImport } from './routes/_dashboardLayout/accountscards/index'
import { Route as DashboardLayoutExpensesNewRouteImport } from './routes/_dashboardLayout/expenses/new'
import { Route as DashboardLayoutAccountscardsNewRouteImport } from './routes/_dashboardLayout/accountscards/new'
import { Route as DashboardLayoutExpensesExpIdEditRouteImport } from './routes/_dashboardLayout/expenses/$expId.edit'
import { Route as DashboardLayoutAccountscardsSourceIdEditRouteImport } from './routes/_dashboardLayout/accountscards/$sourceId.edit'
import { Route as AuthLayoutVerifyUidb64TokenRouteImport } from './routes/_authLayout/verify.$uidb64.$token'

const DashboardLayoutRouteRoute = DashboardLayoutRouteRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRouteRoute = AuthLayoutRouteRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutDashboardRoute =
  DashboardLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const AuthLayoutSignupRoute = AuthLayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutCheckEmailVerifyRoute =
  AuthLayoutCheckEmailVerifyRouteImport.update({
    id: '/check-email-verify',
    path: '/check-email-verify',
    getParentRoute: () => AuthLayoutRouteRoute,
  } as any)
const DashboardLayoutExpensesIndexRoute =
  DashboardLayoutExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAccountscardsIndexRoute =
  DashboardLayoutAccountscardsIndexRouteImport.update({
    id: '/accountscards/',
    path: '/accountscards/',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutExpensesNewRoute =
  DashboardLayoutExpensesNewRouteImport.update({
    id: '/expenses/new',
    path: '/expenses/new',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAccountscardsNewRoute =
  DashboardLayoutAccountscardsNewRouteImport.update({
    id: '/accountscards/new',
    path: '/accountscards/new',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutExpensesExpIdEditRoute =
  DashboardLayoutExpensesExpIdEditRouteImport.update({
    id: '/expenses/$expId/edit',
    path: '/expenses/$expId/edit',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const DashboardLayoutAccountscardsSourceIdEditRoute =
  DashboardLayoutAccountscardsSourceIdEditRouteImport.update({
    id: '/accountscards/$sourceId/edit',
    path: '/accountscards/$sourceId/edit',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const AuthLayoutVerifyUidb64TokenRoute =
  AuthLayoutVerifyUidb64TokenRouteImport.update({
    id: '/verify/$uidb64/$token',
    path: '/verify/$uidb64/$token',
    getParentRoute: () => AuthLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-email-verify': typeof AuthLayoutCheckEmailVerifyRoute
  '/login': typeof AuthLayoutLoginRoute
  '/signup': typeof AuthLayoutSignupRoute
  '/dashboard': typeof DashboardLayoutDashboardRoute
  '/accountscards/new': typeof DashboardLayoutAccountscardsNewRoute
  '/expenses/new': typeof DashboardLayoutExpensesNewRoute
  '/accountscards': typeof DashboardLayoutAccountscardsIndexRoute
  '/expenses': typeof DashboardLayoutExpensesIndexRoute
  '/verify/$uidb64/$token': typeof AuthLayoutVerifyUidb64TokenRoute
  '/accountscards/$sourceId/edit': typeof DashboardLayoutAccountscardsSourceIdEditRoute
  '/expenses/$expId/edit': typeof DashboardLayoutExpensesExpIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-email-verify': typeof AuthLayoutCheckEmailVerifyRoute
  '/login': typeof AuthLayoutLoginRoute
  '/signup': typeof AuthLayoutSignupRoute
  '/dashboard': typeof DashboardLayoutDashboardRoute
  '/accountscards/new': typeof DashboardLayoutAccountscardsNewRoute
  '/expenses/new': typeof DashboardLayoutExpensesNewRoute
  '/accountscards': typeof DashboardLayoutAccountscardsIndexRoute
  '/expenses': typeof DashboardLayoutExpensesIndexRoute
  '/verify/$uidb64/$token': typeof AuthLayoutVerifyUidb64TokenRoute
  '/accountscards/$sourceId/edit': typeof DashboardLayoutAccountscardsSourceIdEditRoute
  '/expenses/$expId/edit': typeof DashboardLayoutExpensesExpIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authLayout': typeof AuthLayoutRouteRouteWithChildren
  '/_dashboardLayout': typeof DashboardLayoutRouteRouteWithChildren
  '/_authLayout/check-email-verify': typeof AuthLayoutCheckEmailVerifyRoute
  '/_authLayout/login': typeof AuthLayoutLoginRoute
  '/_authLayout/signup': typeof AuthLayoutSignupRoute
  '/_dashboardLayout/dashboard': typeof DashboardLayoutDashboardRoute
  '/_dashboardLayout/accountscards/new': typeof DashboardLayoutAccountscardsNewRoute
  '/_dashboardLayout/expenses/new': typeof DashboardLayoutExpensesNewRoute
  '/_dashboardLayout/accountscards/': typeof DashboardLayoutAccountscardsIndexRoute
  '/_dashboardLayout/expenses/': typeof DashboardLayoutExpensesIndexRoute
  '/_authLayout/verify/$uidb64/$token': typeof AuthLayoutVerifyUidb64TokenRoute
  '/_dashboardLayout/accountscards/$sourceId/edit': typeof DashboardLayoutAccountscardsSourceIdEditRoute
  '/_dashboardLayout/expenses/$expId/edit': typeof DashboardLayoutExpensesExpIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-email-verify'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/accountscards/new'
    | '/expenses/new'
    | '/accountscards'
    | '/expenses'
    | '/verify/$uidb64/$token'
    | '/accountscards/$sourceId/edit'
    | '/expenses/$expId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-email-verify'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/accountscards/new'
    | '/expenses/new'
    | '/accountscards'
    | '/expenses'
    | '/verify/$uidb64/$token'
    | '/accountscards/$sourceId/edit'
    | '/expenses/$expId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authLayout'
    | '/_dashboardLayout'
    | '/_authLayout/check-email-verify'
    | '/_authLayout/login'
    | '/_authLayout/signup'
    | '/_dashboardLayout/dashboard'
    | '/_dashboardLayout/accountscards/new'
    | '/_dashboardLayout/expenses/new'
    | '/_dashboardLayout/accountscards/'
    | '/_dashboardLayout/expenses/'
    | '/_authLayout/verify/$uidb64/$token'
    | '/_dashboardLayout/accountscards/$sourceId/edit'
    | '/_dashboardLayout/expenses/$expId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
  DashboardLayoutRouteRoute: typeof DashboardLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/dashboard': {
      id: '/_dashboardLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutDashboardRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_authLayout/signup': {
      id: '/_authLayout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthLayoutSignupRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/login': {
      id: '/_authLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/check-email-verify': {
      id: '/_authLayout/check-email-verify'
      path: '/check-email-verify'
      fullPath: '/check-email-verify'
      preLoaderRoute: typeof AuthLayoutCheckEmailVerifyRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_dashboardLayout/expenses/': {
      id: '/_dashboardLayout/expenses/'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof DashboardLayoutExpensesIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/accountscards/': {
      id: '/_dashboardLayout/accountscards/'
      path: '/accountscards'
      fullPath: '/accountscards'
      preLoaderRoute: typeof DashboardLayoutAccountscardsIndexRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/expenses/new': {
      id: '/_dashboardLayout/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof DashboardLayoutExpensesNewRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/accountscards/new': {
      id: '/_dashboardLayout/accountscards/new'
      path: '/accountscards/new'
      fullPath: '/accountscards/new'
      preLoaderRoute: typeof DashboardLayoutAccountscardsNewRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/expenses/$expId/edit': {
      id: '/_dashboardLayout/expenses/$expId/edit'
      path: '/expenses/$expId/edit'
      fullPath: '/expenses/$expId/edit'
      preLoaderRoute: typeof DashboardLayoutExpensesExpIdEditRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_dashboardLayout/accountscards/$sourceId/edit': {
      id: '/_dashboardLayout/accountscards/$sourceId/edit'
      path: '/accountscards/$sourceId/edit'
      fullPath: '/accountscards/$sourceId/edit'
      preLoaderRoute: typeof DashboardLayoutAccountscardsSourceIdEditRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/_authLayout/verify/$uidb64/$token': {
      id: '/_authLayout/verify/$uidb64/$token'
      path: '/verify/$uidb64/$token'
      fullPath: '/verify/$uidb64/$token'
      preLoaderRoute: typeof AuthLayoutVerifyUidb64TokenRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
  }
}

interface AuthLayoutRouteRouteChildren {
  AuthLayoutCheckEmailVerifyRoute: typeof AuthLayoutCheckEmailVerifyRoute
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutSignupRoute: typeof AuthLayoutSignupRoute
  AuthLayoutVerifyUidb64TokenRoute: typeof AuthLayoutVerifyUidb64TokenRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayoutCheckEmailVerifyRoute: AuthLayoutCheckEmailVerifyRoute,
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutSignupRoute: AuthLayoutSignupRoute,
  AuthLayoutVerifyUidb64TokenRoute: AuthLayoutVerifyUidb64TokenRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

interface DashboardLayoutRouteRouteChildren {
  DashboardLayoutDashboardRoute: typeof DashboardLayoutDashboardRoute
  DashboardLayoutAccountscardsNewRoute: typeof DashboardLayoutAccountscardsNewRoute
  DashboardLayoutExpensesNewRoute: typeof DashboardLayoutExpensesNewRoute
  DashboardLayoutAccountscardsIndexRoute: typeof DashboardLayoutAccountscardsIndexRoute
  DashboardLayoutExpensesIndexRoute: typeof DashboardLayoutExpensesIndexRoute
  DashboardLayoutAccountscardsSourceIdEditRoute: typeof DashboardLayoutAccountscardsSourceIdEditRoute
  DashboardLayoutExpensesExpIdEditRoute: typeof DashboardLayoutExpensesExpIdEditRoute
}

const DashboardLayoutRouteRouteChildren: DashboardLayoutRouteRouteChildren = {
  DashboardLayoutDashboardRoute: DashboardLayoutDashboardRoute,
  DashboardLayoutAccountscardsNewRoute: DashboardLayoutAccountscardsNewRoute,
  DashboardLayoutExpensesNewRoute: DashboardLayoutExpensesNewRoute,
  DashboardLayoutAccountscardsIndexRoute:
    DashboardLayoutAccountscardsIndexRoute,
  DashboardLayoutExpensesIndexRoute: DashboardLayoutExpensesIndexRoute,
  DashboardLayoutAccountscardsSourceIdEditRoute:
    DashboardLayoutAccountscardsSourceIdEditRoute,
  DashboardLayoutExpensesExpIdEditRoute: DashboardLayoutExpensesExpIdEditRoute,
}

const DashboardLayoutRouteRouteWithChildren =
  DashboardLayoutRouteRoute._addFileChildren(DashboardLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
  DashboardLayoutRouteRoute: DashboardLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
